# Generated by Django 4.1.1 on 2022-09-19 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_published_at_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 19, 6, 33, 31, 910272, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
