# Generated by Django 4.1.1 on 2022-09-19 06:34

import datetime
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("blog", "0004_alter_post_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 9, 19, 6, 34, 11, 353171, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
